<a href="https://colab.research.google.com/github/mkmahto2/summerintership_goeduhub/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Assignment/Task-4***


### **GO_STP_9639**

# ***Import the numpy package and print numpy version and configuration***

In [ ]:
import numpy as np

np.version


<module 'numpy.version' from '/usr/local/lib/python3.7/dist-packages/numpy/version.py'>

# ***Create a null vector of size 10***

In [ ]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# ***Create simple 1-D array and check type and data types in array***

In [ ]:
a = np.array([1,2,3,4])

print(type(a))

a.dtype

<class 'numpy.ndarray'>


dtype('int64')

# ***How to find number of dimensions, bytes per element and bytes of memory used ?***

In [ ]:
## Dimensions
print(a.ndim)
## Bytes per element
print(a.itemsize)
## Total Memory used
print(a.nbytes)

1
8
32


# ***Create a null vector of size 10 but the fifth value which is 1***

In [ ]:
null = np.zeros(10)
null[4] = 1

print(null)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# ***Create a vector with values ragging from 10 to 49***

In [ ]:
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# ***Reverse a vector (first element becomes last element)***

In [ ]:
a = np.arange(10)
a = a[::-1]

print(a)

[9 8 7 6 5 4 3 2 1 0]


# ***Create a 3x3 Matrix with values ragging 0 to 8***

In [ ]:
a = np.arange(0,9).reshape(3,3)

print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# ***Find the indices of non-zero elements from [1,2,0,0,4,0]***

In [ ]:
x = np.array([1,2,0,0,4,0])

print(x.nonzero())

(array([0, 1, 4]),)


# ***Create 3x3 Identity Matrix***

In [ ]:
x = np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# ***Create 3x3x3 array with random values.***

In [ ]:
x = np.random.random((3,3,3))
print(x)

[[[0.99648328 0.70975426 0.02683504]
  [0.08394911 0.51561489 0.51650198]
  [0.52200435 0.04836888 0.24233779]]

 [[0.29260685 0.97549055 0.432912  ]
  [0.89996365 0.20224729 0.39582076]
  [0.24457678 0.92085903 0.28975352]]

 [[0.46996427 0.02824502 0.87771572]
  [0.12561839 0.0034517  0.11260609]
  [0.11208388 0.99436697 0.33148014]]]


# ***Create a 10x10 array with random values and find maximun and minimun***

In [ ]:
x = np.random.random((10,10))
print(x.min())
print(x.max())


0.006925541862780715
0.9988474143710147


# ***Create a random vector of size 30 and find the mean values***

In [ ]:
x = np.arange(30)
print(x.mean())

14.5


# ***Create a 2-D array with 1 on border and 0 inside***

In [ ]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# ***How to add a border (filled with 0's) around an existing array?***

In [ ]:
x = np.pad(x, pad_width=1, mode='constant',constant_values=0)
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


# ***How to accessing/changing specific elements, rows, columns, etc in Numpy array?***

In [ ]:
x = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

## Get Element 13
print(x[1,5])

# Get Only 1st Row
print(x[1:])

# Get 3rd Column only
print(x[0:,3])

# Get [2,4,6]
print(x[0,:][1:6:2])

# Replace 13 by 20
x[1,5] = 20

print(x)

13
[[ 8  9 10 11 12 13 14]]
[ 4 11]
[2 4 6]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


# ***How to convert a 1D array to a 2D array with 2 rows***

In [ ]:
x = np.array([1,2,3,4,5,6,7,8])
newarr = x.reshape(2,4)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]]


# ***Create the following pattern without hardcoding, Use only numpy functions and the below input array.***

In [ ]:
a = np.array([1,2,3])
x = np.r_[np.repeat(a, 3), np.tile(a, 3)]

print(x)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


# ***Write a program to show how numpy taking less memory compared to Python List***

In [ ]:
import sys

# Declaring a list of 3000 elements

l = range(3000)
# Printing the size of each element in the list
print("List each element size : ", sys.getsizeof(l))
# Print size of whole list in bytes
print("Whole size of list : " , sys.getsizeof(l) * len(l))

# Declaring an Numpy array

numpyarr = np.arange(3000)
# Printing the size of each element in the numpy array
print("Numpy array each element size : ", numpyarr.itemsize)
# Print size of whole numpy array in bytes
print("Whole size of numpy array : " , numpyarr.size * numpyarr.itemsize)


List each element size :  48
Whole size of list :  144000
Numpy array each element size :  8
Whole size of numpy array :  24000


# ***Write a program to show how Numpy taking less time compared to python List***

In [ ]:
import time
# Declaring a list of 3000 elements
l1 = range(3000)
l2 = range(3000)
# Declaring an Numpy array
numpyarr1 = np.arange(3000)
numpyarr2 = np.arange(3000)

intialTime = time.time()

resulttime = [(l1 + l2) for l1, l2 in zip(l1, l2)]

# Calculation of execution time
print("Time taken by lists to perform addition : ", (time.time() - intialTime) , "Seconds")

intialTime = time.time()

resultant = numpyarr1 + numpyarr2 

# Calculation of execution time
print("Time taken by Numpy arrays to perform addition : ", (time.time() - intialTime) , "Seconds")


Time taken by lists to perform addition :  0.0012340545654296875 Seconds
Time taken by Numpy arrays to perform addition :  0.002310514450073242 Seconds
